export enum ACTION_TYPE {
  INTERNAL_FUND_TRANSFER = 'INTERNAL_FUND_TRANSFER',
  INITIATE_PAYOUT = 'INITIATE_PAYOUT',
  DELETE = 'DELETE',
}

export enum MODAL_TYPE {
  INTERNAL_FUND_TRANSFER = 'INTERNAL_FUND_TRANSFER',
  INTERNAL_FUND_TRANSFER_SUCCESS = 'INTERNAL_FUND_TRANSFER_SUCCESS',

  INITIATE_PAYOUT = 'INITIATE_PAYOUT',
  INITIATE_PAYOUT_SUCCESS = 'INITIATE_PAYOUT_SUCCESS',
  INITIATE_PAYOUT_FAILED = 'INITIATE_PAYOUT_FAILED',
  INITIATE_PAYOUT_PENDING = 'INITIATE_PAYOUT_PENDING',

  ADD_BENEFICIARY = 'ADD_BENEFICIARY',

  ALLOCATE_FUNDS = 'ALLOCATE_FUNDS',
  ALLOCATE_FUNDS_SUCCESS = 'ALLOCATE_FUNDS_SUCCESS',
  ALLOCATE_FUNDS_FAILED = 'ALLOCATE_FUNDS_FAILED',

  DELETE = 'DELETE',

  EMPTY = '',
}

export const REQUIRED_FIELDS = {
  [MODAL_TYPE.INTERNAL_FUND_TRANSFER]: [
    'amount',
    'paymentInstrumentId',
    'toPaymentInstrumentId',
  ],
  [MODAL_TYPE.ALLOCATE_FUNDS]: ['amount', 'toPaymentInstrumentId'],
};
