import React from 'react';
import moment from 'moment';
import { Space, Popup } from '@cashfree-intl/coherent';

// Constants
import { FORMATS } from 'constants/date';

// Components
import CanWrite from 'components/CanWrite';
import Icon from 'components/Icon';
import StatusLabel from 'components/StatusLabel';

// Styled
import { Action } from 'styled/common';

// Types
import type { IPRow, PublicKeyRow } from './types';

export const getFormattedRowData = (
  isIP: boolean,
  handleIPDelete: (row: IPRow) => () => void,
  handlePublicKeyDelete: () => void,
) => {
  const ipColumns = [
    {
      accessorKey: 'addedOn',
      header: 'Date & Time',
      ellipsis: true,
      toolTip: true,
      cell: (row: IPRow) => moment(row.addedOn).format(FORMATS.TIMESTAMP),
    },
    {
      accessorKey: 'generatedBy',
      header: 'Generated By',
      ellipsis: true,
      toolTip: true,
      cell: (row: IPRow) => row.generatedBy || '–',
    },
    {
      accessorKey: 'merchantIP',
      header: 'IP Address',
      ellipsis: true,
      toolTip: true,
    },
    {
      accessorKey: 'status',
      header: 'Status',
      cell: (row: IPRow) => (
        <StatusLabel>
          {row.isApproved ? 'ACTIVE' : 'PENDING_APPROVAL'}
        </StatusLabel>
      ),
    },
    {
      accessorKey: 'actions',
      header: 'Actions',
      textAlign: 'right',
      cell: (row: IPRow) => (
        <CanWrite code={22002}>
          <Space justifyContent="flex-end" className="pr-2">
            <Popup
              position="bottom"
              content="Delete"
              trigger={
                <Action onClick={handleIPDelete(row)}>
                  <Icon name="delete" />
                </Action>
              }
            />
          </Space>
        </CanWrite>
      ),
    },
  ];

  const publicKeyColumns = [
    {
      accessorKey: 'addedOn',
      header: 'Date & Time',
      ellipsis: true,
      toolTip: true,
      cell: (row: PublicKeyRow) =>
        moment(row.addedOn).format(FORMATS.TIMESTAMP),
    },
    {
      accessorKey: 'generatedBy',
      header: 'Generated By',
      ellipsis: true,
      toolTip: true,
      cell: (row: PublicKeyRow) => row.generatedBy || '–',
    },
    {
      accessorKey: 'publicKey',
      header: 'Public Key',
      ellipsis: true,
      toolTip: true,
      cell: () => 'xxxxxxxxxxxxxxxx',
    },
    {
      accessorKey: 'actions',
      header: 'Actions',
      textAlign: 'right',
      cell: () => (
        <CanWrite code={22002}>
          <Space justifyContent="flex-end" className="pr-2">
            <Popup
              position="bottom"
              content="Delete"
              trigger={
                <Action onClick={handlePublicKeyDelete}>
                  <Icon name="delete" />
                </Action>
              }
            />
          </Space>
        </CanWrite>
      ),
    },
  ];

  return isIP ? ipColumns : publicKeyColumns;
};
