import moment from 'moment';

export const descByBankStatus = {
  SUCCESS: {
    SENT_TO_BENEFICIARY:
      'Transfer sent to beneficiary bank, awaiting credit confirmation from beneficiary bank',
    COMPLETED: 'Transaction is completed',
  },

  PENDING: {
    BENE_VERIFICATION_PENDING: 'The transfers are under process',
    DUPLICATE: 'The transfers are under process',
    ERROR_FETCHING_STATUS: 'The transfers are under process',
    IN_PROCESS: 'The transfers are under process',
    SOURCE_LIMIT_REACHED: 'The transfers are under process',
    TRANSACTION_PROCESSED: 'The transfers are under process',
    REQUEST_TIMEDOUT:
      'Request timed out with partner bank, transfer in process',
    SUSPECT: 'Transfers flagged as suspicious, under review',
  },

  FAILED: {
    ACCOUNT_BLOCKED: 'Customer bank account is blocked/ frozen',
    FAILED: 'No explicit failure reason from the bank',
    BENE_BANK_DECLINED: 'Transfer request rejected by the beneficiary bank',
    BENEFICIARY_BANK_OFFLINE: 'Beneficiary bank is offline',
    DEST_LIMIT_REACHED: 'Transfer limit to beneficiary exceeded',
    BENE_NAME_DIFFERS: 'Beneficiary name does not match ',
    IMPS_MODE_FAIL: 'IMPS mode not supported for the beneficiary',
    INSUFFICIENT_BALANCE: 'Insufficient balance',
    AUTHENTICATION_FAILURE: 'Failures due to Internal server error',
    BAD_GATEWAY: 'Failures due to Internal server error',
    'DB Internal Server Error': 'Failures due to Internal server error',
    WAIT_TIME_EXCEEDED: 'Failures due to Internal server error',
    INVALID_ACCOUNT_FAIL: 'The account details are Invalid',
    INVALID_BENE_VPA: 'The account details are Invalid',
    INVALID_AMOUNT_FAIL: 'The amount is invalid for the given transfer mode',
    INVALID_IFSC_FAIL: 'The IFSC entered is Invalid',
    INVALID_MODE_FAIL: 'Transfer mode not supported for beneficiary',
    NPCI_UNAVAILABLE: 'NPCI is unavailable',
    NRE_ACCOUNT_FAIL: 'Customer bank account is an NRE account',
    BANK_GATEWAY_ERROR: 'Technical error at the bank',
    CONNECTION_TIMEOUT: 'Technical error at the bank',
    DEBIT_FAILURE: 'Technical error at the bank',
    INVALID_REQUEST: 'Technical error at the bank',
    NO_SUCH_REQUEST: 'Technical error at the bank',
    REINITIALIZE_TRANSFER_LATER: 'Technical error at the bank',
    SOURCE_BANK_DECLINED: 'Technical error at the bank',
    SOURCE_LIMIT_REACHED: 'Partner Bank Issue',
    RTGS_MODE_FAIL: 'RTGS mode not supported for beneficiary',
  },

  REVERSED: {
    ACCOUNT_BLOCKED: 'Customer bank account is blocked/ frozen',
    ACCOUNT_CLOSED: 'Customer bank account is blocked/frozen',
    ACCOUNT_FROZEN: 'Customer bank account is blocked/frozen',
    ACCOUNT_FROZEN_OR_BLOCKED: 'Customer bank account is blocked/frozen',
    ACCOUNT_FROZEN_OR_CLOSED: 'Customer bank account is blocked/frozen',
    ACCOUNT_ON_HOLD: 'Customer bank account is blocked/frozen',
    ACCOUNT_DOES_NOT_EXIST: 'Account does not exist',
    ANY_OTHER_REASON: 'No explicit failure reason provided from the bank',
    FAILED: 'No explicit failure reason from the bank',
    BENE_BANK_DECLINED: 'Transfer request rejected by the beneficiary bank',
    BENEFICIARY_BANK_OFFLINE: 'Beneficiary bank is offline',
    BENEFICIARY_NAME_DIFFERS: 'Beneficiary name does not match',
    DEST_LIMIT_REACHED: 'Transfer limit to beneficiary exceeded',
    BENE_NAME_DIFFERS: 'Beneficiary name does not match ',
    CREDIT_LIMIT_EXCEEDED: 'Transfer limit to beneficiary exceeded',
    IFSC_DOES_NOT_MATCH: 'IFSC does not match',
    IMPS_MODE_FAIL: 'IMPS mode not supported for the beneficiary',
    INVALID_ACCOUNT_FAIL: 'The account details are Invalid',
    INVALID_OR_NO_SUCH_ACCOUNT_TYPE: 'The account details are Invalid',
    NRE_ACCOUNT_FAIL: 'Customer bank account is an NRE account',
    REINITIALIZE_TRANSFER_LATER: 'Technical error at the bank',
    RETURNED_FROM_BENEFICIARY:
      'Transfer request rejected by the beneficiary bank',
    FRAUD_REVERSED: 'Transfers flagged as suspicious',
  },

  REJECTED: {
    BENE_BLACKLISTED: 'The beneficiary account is Blacklisted',
    BENE_NOT_EXIST: 'Beneficiary does not exist',
    INSUFFICIENT_BALANCE: 'Insufficient balance',
    'Could not connect to internal': 'Failures due to Internal server error',
    'DB Internal Server Error': 'Failures due to Internal server error',
    'Internal Server Error': 'Failures due to Internal server error',
    TRANSFER_NOT_ATTEMPTED: 'Failures due to Internal server error',
    VELOCITY_CHECK_FAILED: 'Failures due to Internal server error',
    INVALID_PAYMENT_INSTRUMENT: 'Payment instrument used is Invalid',
    DISABLED_MODE: 'Transfer mode is Invalid',
    INVALID_MODE_FOR_PYID: 'Transfer mode is Invalid',
  },
};

export const labelByBankStatus = {
  SUCCESS: {
    SENT_TO_BENEFICIARY: 'Sent To Beneficiary',
    COMPLETED: 'Transaction Completed',
  },

  PENDING: {
    BENE_VERIFICATION_PENDING: 'In Process',
    DUPLICATE: 'In Process',
    ERROR_FETCHING_STATUS: 'In Process',
    IN_PROCESS: 'In Process',
    SOURCE_LIMIT_REACHED: 'In Process',
    TRANSACTION_PROCESSED: 'In Process',
    REQUEST_TIMEDOUT: 'Partner Bank Issue',
    SUSPECT: 'Suspicious Transfer',
  },

  FAILED: {
    ACCOUNT_BLOCKED: 'Account Blocked/Frozen',
    FAILED: 'Any Other Reason',
    BENE_BANK_DECLINED: 'Beneficiary Bank Decline',
    BENEFICIARY_BANK_OFFLINE: 'Beneficiary Bank Offline',
    DEST_LIMIT_REACHED: 'Beneficiary Limit Reached',
    BENE_NAME_DIFFERS: 'Beneficiary Name Mismatch',
    IMPS_MODE_FAIL: 'IMPS Mode Fail',
    INSUFFICIENT_BALANCE: 'Insufficient Balance',
    AUTHENTICATION_FAILURE: 'Internal Server Error',
    BAD_GATEWAY: 'Internal Server Error',
    'DB Internal Server Error': 'Internal Server Error',
    WAIT_TIME_EXCEEDED: 'Internal Server Error',
    INVALID_ACCOUNT_FAIL: 'Invalid Account Details',
    INVALID_BENE_VPA: 'Invalid Account Details',
    INVALID_AMOUNT_FAIL: 'Invalid Amount',
    INVALID_IFSC_FAIL: 'Invalid IFSC fail',
    INVALID_MODE_FAIL: 'Invalid Transfer Mode',
    NPCI_UNAVAILABLE: 'NPCI Unavailable',
    NRE_ACCOUNT_FAIL: 'NRE Account Fail',
    BANK_GATEWAY_ERROR: 'Partner Bank Issue',
    CONNECTION_TIMEOUT: 'Partner Bank Issue',
    DEBIT_FAILURE: 'Partner Bank Issue',
    INVALID_REQUEST: 'Partner Bank Issue',
    NO_SUCH_REQUEST: 'Partner Bank Issue',
    REINITIALIZE_TRANSFER_LATER: 'Partner Bank Issue',
    SOURCE_BANK_DECLINED: 'Partner Bank Issue',
    SOURCE_LIMIT_REACHED: 'Partner Bank Issue',
    RTGS_MODE_FAIL: 'RTGS Mode Fail',
  },

  REVERSED: {
    ACCOUNT_BLOCKED: 'Account Blocked/Frozen',
    ACCOUNT_CLOSED: 'Account Blocked/Frozen',
    ACCOUNT_FROZEN: 'Account Blocked/Frozen',
    ACCOUNT_FROZEN_OR_BLOCKED: 'Account Blocked/Frozen',
    ACCOUNT_FROZEN_OR_CLOSED: 'Account Blocked/Frozen',
    ACCOUNT_ON_HOLD: 'Account Blocked/Frozen',
    ACCOUNT_DOES_NOT_EXIST: 'Account Not Exists',
    ANY_OTHER_REASON: 'No explicit failure reason provided from the bank',
    FAILED: 'Any Other Reason',
    BENE_BANK_DECLINED: 'Beneficiary Bank Decline',
    BENEFICIARY_BANK_OFFLINE: 'Beneficiary Bank Offline',
    BENEFICIARY_NAME_DIFFERS: 'Beneficiary Name Mismatch',
    DEST_LIMIT_REACHED: 'Beneficiary Limit Reached',
    BENE_NAME_DIFFERS: 'Beneficiary Name Mismatch',
    CREDIT_LIMIT_EXCEEDED: 'Credit Limit Reached',
    IFSC_DOES_NOT_MATCH: 'IFSC Mismatch',
    IMPS_MODE_FAIL: 'IMPS Mode Fail',
    INVALID_ACCOUNT_FAIL: 'Invalid Account Details',
    INVALID_OR_NO_SUCH_ACCOUNT_TYPE: 'Invalid Account Details',
    NRE_ACCOUNT_FAIL: 'NRE Account Fail',
    REINITIALIZE_TRANSFER_LATER: 'Partner Bank Issue',
    RETURNED_FROM_BENEFICIARY: 'Returned From Beneficiary',
    FRAUD_REVERSED: 'Suspicious Transfer',
  },

  REJECTED: {
    BENE_BLACKLISTED: 'Beneficiary Blacklisted',
    BENE_NOT_EXIST: 'Beneficiary Not Exists',
    INSUFFICIENT_BALANCE: 'Insufficient Balance',
    'Could not connect to internal': 'Internal Server Error',
    'DB Internal Server Error': 'Internal Server Error',
    'Internal Server Error': 'Internal Server Error',
    TRANSFER_NOT_ATTEMPTED: 'Internal Server Error',
    VELOCITY_CHECK_FAILED: 'Internal Server Error',
    INVALID_PAYMENT_INSTRUMENT: 'Invalid payment Instrument',
    DISABLED_MODE: 'Transfer Mode Invalid',
    INVALID_MODE_FOR_PYID: 'Transfer Mode Invalid',
  },
};

export const COLLATE_MAP = {
  PENDING: {
    BENE_VERIFICATION_PENDING: 'IN_PROCESS',
    DUPLICATE: 'IN_PROCESS',
    ERROR_FETCHING_STATUS: 'IN_PROCESS',
    IN_PROCESS: 'IN_PROCESS',
    SOURCE_LIMIT_REACHED: 'IN_PROCESS',
    TRANSACTION_PROCESSED: 'IN_PROCESS',
  },

  FAILED: {
    AUTHENTICATION_FAILURE: 'BAD_GATEWAY',
    BAD_GATEWAY: 'BAD_GATEWAY',
    'DB Internal Server Error': 'BAD_GATEWAY',
    WAIT_TIME_EXCEEDED: 'BAD_GATEWAY',

    INVALID_ACCOUNT_FAIL: 'INVALID_ACCOUNT_FAIL',
    INVALID_BENE_VPA: 'INVALID_ACCOUNT_FAIL',

    BANK_GATEWAY_ERROR: 'SOURCE_BANK_DECLINED',
    CONNECTION_TIMEOUT: 'SOURCE_BANK_DECLINED',
    DEBIT_FAILURE: 'SOURCE_BANK_DECLINED',
    INVALID_REQUEST: 'SOURCE_BANK_DECLINED',
    NO_SUCH_REQUEST: 'SOURCE_BANK_DECLINED',
    REINITIALIZE_TRANSFER_LATER: 'SOURCE_BANK_DECLINED',
    SOURCE_BANK_DECLINED: 'SOURCE_BANK_DECLINED',
    SOURCE_LIMIT_REACHED: 'SOURCE_BANK_DECLINED',
  },

  REVERSED: {
    ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
    ACCOUNT_CLOSED: 'ACCOUNT_BLOCKED',
    ACCOUNT_FROZEN: 'ACCOUNT_BLOCKED',
    ACCOUNT_FROZEN_OR_BLOCKED: 'ACCOUNT_BLOCKED',
    ACCOUNT_FROZEN_OR_CLOSED: 'ACCOUNT_BLOCKED',
    ACCOUNT_ON_HOLD: 'ACCOUNT_BLOCKED',
  },
};

export const STATUS_MAP = {
  SUCCESS: Object.keys(labelByBankStatus.SUCCESS),
  PENDING: Object.keys(labelByBankStatus.PENDING),
  FAILED: Object.keys(labelByBankStatus.FAILED),
  REVERSED: Object.keys(labelByBankStatus.REVERSED),
  REJECTED: Object.keys(labelByBankStatus.REJECTED),
};

export const TODAY = moment().format('YYYY-MM-DD');
