import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import _get from 'lodash/get';

// Utils
import { getConfigs } from '../utils';

// Services
import * as ReportsService from 'services/reports';

// Constants
import { accountProviderMock } from '__mocks__/common.mock';
import { MODAL_TYPES } from '../constants';

// Components
import Wrapper from '__tests__/components/Wrapper';
import Modals from '../components/Modals';

// Containers
import Reports from '..';

const { validReportTypes } = getConfigs(
  _get(accountProviderMock, 'preferences.activated'),
);

beforeEach(() => {
  jest.mock('services/reports');

  jest.spyOn(ReportsService, 'getReports').mockImplementation(() =>
    Promise.resolve({
      entries: [
        {
          id: '679466',
          type: 'ACCOUNT',
          reportName: 'Account Statement-17-11-2022',
          size: 316,
          addedOn: '2022-11-17 18:21:07',
          generatedBy: 'Rahul Mallik',
          status: 'READY',
          format: 'CSV',
        },
        {
          id: '679465',
          type: 'TRANSFER',
          reportName: 'Transfer-17-11-2022',
          size: 1145,
          addedOn: '2022-11-17 18:18:53',
          generatedBy: 'Adarsh',
          status: 'READY',
          format: 'CSV',
        },
      ],
      size: 2,
      num: 0,
      total: 2,
    }),
  );

  jest
    .spyOn(ReportsService, 'deleteReport')
    .mockImplementation(() => Promise.resolve({}));

  jest
    .spyOn(ReportsService, 'generateReport')
    .mockImplementation(() => Promise.resolve({}));
});

afterEach(() => {
  jest.resetAllMocks();
  jest.clearAllMocks();
});

describe('In Reports Container', () => {
  test('checks render', async () => {
    render(<Reports />, { wrapper: Wrapper });

    await waitFor(() => {
      expect(ReportsService.getReports).toHaveBeenCalledWith(
        expect.objectContaining({
          reportType: [
            'ACCOUNT',
            'BANK_VALIDATION',
            'PAN_VERIFICATION',
            'AADHAAR_VERIFICATION',
            'GSTIN_VERIFICATION',
            'OFFLINE_AADHAAR_VERIFICATION',
            'IFSC_VERIFICATION',
            'UPI_FROM_MOBILE_NUMBER',
            'REVERSE_PENNY_DROP',
          ],
          size: 10,
          lastId: '0',
        }),
      );

      expect(screen.queryByText('Generated Reports')).toBeInTheDocument();
      expect(screen.queryByText('Generated At')).toBeInTheDocument();
      expect(screen.queryByText('Generated By')).toBeInTheDocument();
      expect(screen.queryByText('Search & Filter')).toBeInTheDocument();
      expect(
        screen.queryByText('Account Statement-17-11-2022.CSV'),
      ).toBeInTheDocument();
      expect(screen.queryByText('Rahul Mallik')).toBeInTheDocument();
    });
  });

  test('<GenerateReportModal />', async () => {
    render(<Reports />, { wrapper: Wrapper });

    fireEvent.click(await screen.findByText(/Select/));

    expect(screen.queryAllByText(validReportTypes[0].name).length).toBe(2);

    expect(await screen.findByText(/Generate Report/)).toBeDisabled();
    fireEvent.click(await screen.findByText(/Select/));
    fireEvent.click(
      await screen.findByText(new RegExp(validReportTypes[0].description, 'i')),
    );

    const generateReportBtn = await screen.findByText(/Generate Report/);
    expect(generateReportBtn).not.toBeDisabled();
    fireEvent.click(generateReportBtn);

    expect(await screen.findByText(/File Format/)).toBeInTheDocument();
    expect(await screen.findByText(/Choose Columns/)).toBeInTheDocument();
  });

  test.skip('checks Modals render', async () => {
    const setModalType = jest.fn();
    const setFetchCounter = jest.fn();
    const setReportType = jest.fn();

    render(
      <Modals
        modalType={MODAL_TYPES.GENERATE}
        setModalType={setModalType}
        setFetchCounter={setFetchCounter}
        setData={jest.fn()}
        selectedRow={{ id: 123, reportName: 'foo bar' }}
        reportType={{
          type: 'TRANSFER',
          name: 'john doe',
          description: 'rainfall',
          columns: [
            { name: 'Added On', value: 'ADDED_ON', checked: true },
            { name: 'Amount', value: 'AMOUNT', checked: true },
          ],
          text: 'foo',
        }}
        setReportType={setReportType}
      />,
      { wrapper: Wrapper },
    );

    expect(screen.queryByText('Show All (2)')).toBeInTheDocument();
    expect(screen.queryByText('Choose Columns')).toBeInTheDocument();

    const submitButton = screen.queryByRole('button', {
      name: 'Generate Report',
    });

    const reportNameInput = screen
      .getByTestId('report-name')
      .querySelector('input');
    expect(reportNameInput).toBeInTheDocument();

    await waitFor(
      async () => {
        await userEvent.clear(reportNameInput);

        await userEvent.type(reportNameInput, 'foobar');
      },
      { timeout: 8000 },
    );
    expect(reportNameInput.value).toBe('foobar');

    const showAllEl = screen.getByTestId('show-all').querySelector('input');

    await userEvent.click(showAllEl);

    expect(setReportType).toHaveBeenCalled();

    expect(submitButton).not.toBeDisabled();
    expect(submitButton).toHaveClass('ml-4');
    expect(submitButton).toBeInTheDocument();

    fireEvent.click(submitButton);

    expect(ReportsService.generateReport).toHaveBeenCalled();

    // expect(setModalType).toHaveBeenCalled();

    const cancelButton = screen.queryByText('Cancel');

    expect(cancelButton).not.toBeDisabled();
    expect(cancelButton).toBeInTheDocument();

    fireEvent.click(cancelButton);

    expect(setModalType).toHaveBeenCalled();
  });

  test('checks Modals render', async () => {
    const setModalType = jest.fn();

    render(
      <Modals
        modalType={MODAL_TYPES.DELETE}
        setModalType={setModalType}
        setFetchCounter={jest.fn()}
        setData={jest.fn()}
        selectedRow={{ id: 123, reportName: 'foo bar' }}
        reportType={{
          type: 'TRANSFER',
          name: 'john doe',
          description: 'rainfall',
          columns: [],
        }}
        setReportType={jest.fn()}
      />,
      { wrapper: Wrapper },
    );

    await waitFor(() => {
      expect(screen.queryByText('Delete Report')).toBeInTheDocument();

      expect(
        screen.queryByText(
          'Are you sure you want to delete the foo bar report?',
        ),
      ).toBeInTheDocument();

      const submitButton = screen.queryByRole('button', {
        name: 'Delete',
      });

      expect(submitButton).toHaveClass('ml-2');
      expect(submitButton).toBeInTheDocument();

      fireEvent.click(submitButton);

      expect(ReportsService.deleteReport).toHaveBeenCalledWith(123);
      expect(setModalType).toHaveBeenCalled();

      const cancelButton = screen.queryByText('Cancel');

      expect(cancelButton).not.toBeDisabled();
      expect(cancelButton).toBeInTheDocument();

      fireEvent.click(cancelButton);

      expect(setModalType).toHaveBeenCalled();
    });
  });
});
