import React from 'react';
import moment from 'moment';
import { toast, Space, EllipsisPopup } from '@cashfree-intl/coherent';
import _capitalize from 'lodash/capitalize';
import _startCase from 'lodash/startCase';

// Components
import Icon from 'components/Icon';
import CanWrite from 'components/CanWrite';
import StatusLabel from 'components/StatusLabel';

// Utils
import { getSizeText } from 'utils/common';
import Region from 'utils/region';

// Constants
import { FORMATS } from 'constants/date';
import { REGION } from 'constants/common';
import { STATUS, ACTION_TYPE } from './constants';

const actions: RowAction<ACTION_TYPE>[] = [
  {
    key: ACTION_TYPE.DOWNLOAD,
    text: 'Download',
    value: ACTION_TYPE.DOWNLOAD,
    image: (props) => <Icon name="download" {...props} />,
  },
  {
    key: ACTION_TYPE.DELETE,
    text: 'Delete',
    value: ACTION_TYPE.DELETE,
    image: (props) => <Icon name="delete" {...props} />,
    type: 'danger',
  },
];

export const getFormattedRowData = (
  handleDownload: (row: AnyObject) => Promise<void>,
  handleDelete: (row: AnyObject) => void,
) => [
  {
    accessorKey: 'type',
    header: 'Type',
    ellipsis: true,
    toolTip: true,
    cell: (row: AnyObject) => _capitalize(_startCase(row.type)) || '–',
  },
  {
    accessorKey: 'reportName',
    header: 'Report Name',
    ellipsis: true,
    toolTip: true,
    cell: (row: AnyObject) => row.reportName || '–',
  },
  {
    accessorKey: 'size',
    header: 'Size',
    textAlign: 'right',
    ellipsis: true,
    toolTip: true,
    cell: (row: AnyObject) => getSizeText(row.size),
  },
  {
    accessorKey: 'addedOn',
    header: 'Generated At',
    ellipsis: true,
    toolTip: true,
    cell: (row: AnyObject) =>
      row.addedOn
        ? (Region.get() === REGION.IN
            ? moment(row.addedOn).add(5.5, 'hours')
            : moment(row.addedOn + 'Z')
          ).format(FORMATS.TIMESTAMP)
        : '–',
  },
  {
    accessorKey: 'generatedBy',
    header: 'Generated By',
    ellipsis: true,
    toolTip: true,
    cell: (row: AnyObject) => row.generatedBy || '–',
  },
  {
    accessorKey: 'action',
    header: 'Actions',
    textAlign: 'center',
    cell: (row: AnyObject) => {
      if (row.status === STATUS.FAILED) {
        return (
          <div className="ml-5">
            <StatusLabel className="mr-2">{row.status}</StatusLabel>
          </div>
        );
      }

      if (row.status !== STATUS.COMPLETED) {
        return (
          <div>
            <StatusLabel
              className="mr-2"
              animation={row.status === STATUS.PROCESSING}
            >
              {row.status}
            </StatusLabel>
          </div>
        );
      }

      const isReportEmpty: boolean = row.size === 0;

      const handleAction = (e: React.MouseEvent, itemSelected: ACTION_TYPE) => {
        switch (itemSelected) {
          case ACTION_TYPE.DOWNLOAD:
            if (isReportEmpty) {
              toast.warn('No records found for the selected period');
            } else {
              handleDownload(row);
            }
            break;

          case ACTION_TYPE.DELETE:
            handleDelete(row);
            break;
        }
      };

      return (
        <CanWrite code={[21505, 26001]}>
          <Space justifyContent="flex-end">
            <EllipsisPopup menuItems={actions} onClick={handleAction} />
          </Space>
        </CanWrite>
      );
    },
  },
];
