sonar.projectKey=payoutwebapp
sonar.projectName=Payout Web Application
sonar.host.url=https://sonar.cashfree.com

sonar.sourceEncoding=UTF-8

sonar.sources=app
# sonar.inclusions=**/*.{ts,tsx,js,jsx}
sonar.exclusions=**/node_modules/**, **/*.d.ts, **/__tests__/**, **/__mocks__/**, **/images/**, app/*.{ts,tsx,js,jsx}, app/*.html, app/containers/App/**, app/containers/BaseLayout/**, app/components/NotificationBar/*, app/components/NotificationPopover/*, app/containers/ERP/**, app/containers/TransferDetails/components/ApproveAndWhiteList.{ts,tsx,js,jsx}, app/constants/**, app/**/constants.{ts,tsx,js,jsx}, app/redux/actions/**, app/components/CustomIcons/index.{ts,tsx,js,jsx}, app/components/SidebarIcons/index.{ts,tsx,js,jsx}, app/**/helpers.{ts,tsx,js,jsx}, app/containers/**/utils.{ts,tsx,js,jsx},  app/containers/**/styled.{ts,tsx,js,jsx}, app/**/Loadable.{ts,tsx,js,jsx}, app/pages/Reports/**, app/pages/RiskShield/**, app/utils/formValidation.{ts,tsx,js,jsx}

# sonar.javascript.file.suffixes=.js,.jsx,.css
sonar.javascript.lcov.reportPaths=coverage/lcov.info