server {
    listen       80;
    server_name  localhost;

    root /usr/share/nginx/html;    

    location = /verificationsuite {
        try_files $uri /verificationsuite/index.html;
    }

    location /verificationsuite/ {
        index /verificationsuite/index.html;
        try_files $uri $uri/index.html /verificationsuite/index.html;
    }

    location = /vswebapp-test {
        try_files $uri /vswebapp-test/index.html;
    }

    location /vswebapp-test/ {
        index /vswebapp-test/index.html;
        try_files $uri $uri/index.html /vswebapp-test/index.html;
    }  

    location = /vswebapp {
        try_files $uri /vswebapp/index.html;
    }

    location /vswebapp/ {
        index /vswebapp/index.html;
        try_files $uri $uri/index.html /vswebapp/index.html;
    }

    error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    error_page 405 =200 $uri;    
}
