sonar.projectKey=vswebapp
sonar.projectName=Verification Suite Web Application
sonar.host.url=https://sonar.cashfree.com

sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.exclusions=app/*.js, app/*.html, app/services/**, app/constants/**, app/**/constants.js, app/redux/actions/**, app/components/IFrame/**, app/containers/**/helpers.js/, app/containers/**/utils.js/, app/containers/**/styled.js, app/**/Loadable.js, **/__tests__/**, **/__mocks__/**, **/images/**, app/containers/App/**, app/containers/**/utils.js, app/components/**/styled.js, app/redux/**, app/containers/App/components/**


sonar.javascript.file.suffixes=.js,.jsx,.css
sonar.javascript.lcov.reportPaths=coverage/lcov.info