export enum MODAL_TYPE {
  CREATE_VIRTUAL_ACCOUNT = 'CREATE_VIRTUAL_ACCOUNT',
  CREATE_VIRTUAL_ACCOUNT_SUCCESS = 'CREATE_VIRTUAL_ACCOUNT_SUCCESS',
  CREATE_VIRTUAL_ACCOUNT_FAILED = 'CREATE_VIRTUAL_ACCOUNT_FAILED',

  INITIATE_PAYOUT = 'INITIATE_PAYOUT',
  INITIATE_PAYOUT_SUCCESS = 'INITIATE_PAYOUT_SUCCESS',
  INITIATE_PAYOUT_FAILED = 'INITIATE_PAYOUT_FAILED',
  INITIATE_PAYOUT_PENDING = 'INITIATE_PAYOUT_PENDING',

  ADD_BENEFICIARY = 'ADD_BENEFICIARY',

  EMPTY = '',
}

export const REQUIRED_FIELDS = {
  [MODAL_TYPE.CREATE_VIRTUAL_ACCOUNT]: ['displayName', 'accountPrefix'],
};

export enum STATUS {
  DEACTIVATED = 'DEACTIVATED',
}
