import React from 'react';
import moment from 'moment';
import { Space, Popup } from '@cashfree-intl/coherent';

// Constants
import { FORMATS } from 'constants/date';

// Components
import Icon from 'components/Icon';
import Copy from 'components/Copy';
import CanWrite from 'components/CanWrite';

// Styled
import { Action, HoverCopy } from 'styled/common';

export const getFormattedRowData = (
  handleAction: (row: AnyObject) => () => void,
) => [
  {
    accessorKey: 'addedOn',
    header: 'Generated At',
    ellipsis: true,
    toolTip: true,
    cell: (row: AnyObject) => moment(row.addedOn).format(FORMATS.TIMESTAMP),
  },
  {
    accessorKey: 'generatedBy',
    header: 'Generated By',
    ellipsis: true,
    toolTip: true,
    cell: (row: AnyObject) => row.generatedBy || '–',
  },
  {
    accessorKey: 'clientId',
    header: 'Client ID',
    ellipsis: true,
    toolTip: true,
    cell: (row: AnyObject) => (
      <HoverCopy>
        <span>{row.clientId}</span>
        <Copy value={row.clientId} />
      </HoverCopy>
    ),
  },
  {
    accessorKey: 'clientSecret',
    header: 'Client Secret',
    ellipsis: true,
    toolTip: true,
  },
  {
    accessorKey: 'actions',
    header: 'Actions',
    textAlign: 'center',
    cell: (row: AnyObject) => (
      <CanWrite code={22004} remove>
        <Space justifyContent="flex-end" className="pr-2">
          <Popup
            position="bottom"
            content="Delete"
            trigger={
              <Action onClick={handleAction(row)}>
                <Icon name="delete" />
              </Action>
            }
          />
        </Space>
      </CanWrite>
    ),
  },
];
