enum COMMON_ACTION_TYPE {
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  NEXT = 'NEXT',
  PREV = 'PREV',
  SET_DATA = 'SET_DATA',
  SET_DATE_VALUE = 'SET_DATE_VALUE',
  SET_FILTERS = 'SET_FILTERS',
  SET_SEARCH_BY = 'SET_SEARCH_BY',
  SET_LIMIT = 'SET_LIMIT',
}

export default COMMON_ACTION_TYPE;
