import React from 'react';
import ShallowRenderer from 'react-test-renderer/shallow';

// Providers
import { TwoFactorProvider } from 'pages/Developers/providers';

// Pages
import Developers from '..';

// Reducers
import { reducers, initialState } from '../reducers';

// Components
import Wrapper from '__tests__/components/Wrapper';

const renderer = new ShallowRenderer();

// eslint-disable-next-line react/prop-types
const CustomWrapper = ({ children }) => (
  <Wrapper>
    <TwoFactorProvider>{children}</TwoFactorProvider>
  </Wrapper>
);

describe('In Developers page', () => {
  test('shallow render & match the snapshot', () => {
    renderer.render(
      <CustomWrapper>
        <Developers />
      </CustomWrapper>,
    );

    const output = renderer.getRenderOutput();
    expect(output).toMatchSnapshot();
  });

  // test('checks Developers', async () => {
  //   render(<Developers />, { wrapper: CustomWrapper });

  //   await waitFor(() => {
  //
  //     expect(screen.queryByText('Generated At')).toBeInTheDocument();
  //     expect(screen.queryByText('Generated By')).toBeInTheDocument();
  //     expect(screen.queryByText('Client ID')).toBeInTheDocument();
  //     expect(screen.queryByText('Client Secret')).toBeInTheDocument();
  //     expect(screen.queryByText('No record found')).toBeInTheDocument();
  //     expect(screen.queryByText('View History')).toBeInTheDocument();
  //     expect(screen.queryByText('Generate API Keys')).toBeInTheDocument();
  //   });
  // });

  test('reducers()', () => {
    expect(reducers({}, { type: 'RESET' })).toStrictEqual(initialState);

    expect(
      reducers(
        {},
        {
          type: 'SET_DATA',
          payload: 'foo',
        },
      ),
    ).toStrictEqual({
      selected2FA: 'foo',
    });

    expect(
      reducers(
        {},
        {
          type: 'SOMETHING',
          payload: 'foo',
        },
      ),
    ).toBeUndefined();
  });
});
