import { DATE_RANGES, FORMATS as SHARED_FORMATS } from '@dashboard-monorepo/shared';

const ALL_TIME = DATE_RANGES.ALL_TIME;
const LAST_30_MINS = DATE_RANGES.LAST_30_MINS;
const TODAY = DATE_RANGES.TODAY;
const LAST_7_DAYS = DATE_RANGES.LAST_7_DAYS;
const LAST_15_DAYS = DATE_RANGES.LAST_15_DAYS;
const LAST_30_DAYS = DATE_RANGES.LAST_30_DAYS;
const LAST_MONTH = DATE_RANGES.LAST_MONTH;
const THIS_YEAR = DATE_RANGES.THIS_YEAR;
const LAST_1_YEAR = DATE_RANGES.LAST_1_YEAR;

export const DATE_RANGE = {
  LAST_30_MINS,
  TODAY,
  ALL_TIME,
  LAST_7_DAYS,
  LAST_15_DAYS,
  LAST_30_DAYS,
  LAST_MONTH,
  THIS_YEAR,
  LAST_1_YEAR,
};

export const DATE_RANGE_OPTIONS = [
  DATE_RANGE.LAST_1_YEAR,
  // DATE_RANGE.ALL_TIME,
  DATE_RANGE.LAST_7_DAYS,
  DATE_RANGE.LAST_15_DAYS,
  DATE_RANGE.LAST_MONTH,
];

export const [, DEFAULT_VALUE] = DATE_RANGE_OPTIONS;

export const FORMATS = SHARED_FORMATS;
