export enum FS_DISPLAY_TYPE {
  CASHFREE_WALLET = 'CF_WALLET',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  CONNECTED_WALLET = 'CONNECTED_WALLET',

  // @DEPRECATED
  PAYTM_WALLET = 'PAYTM_WALLET',
  CREDIT_CARD = 'CREDIT_CARD',
  UNO_WALLET = 'UNO_WALLET',
}

export const LABEL_BY_DISPLAY_TYPE = {
  [FS_DISPLAY_TYPE.CASHFREE_WALLET]: 'Cashfree Wallet',
  [FS_DISPLAY_TYPE.BANK_ACCOUNT]: 'Bank Account',
  [FS_DISPLAY_TYPE.CONNECTED_WALLET]: 'Connected Wallet',

  // @DEPRECATED
  [FS_DISPLAY_TYPE.PAYTM_WALLET]: 'Paytm Wallet',
  [FS_DISPLAY_TYPE.CREDIT_CARD]: 'Corporate Credit Card',
  [FS_DISPLAY_TYPE.UNO_WALLET]: 'Uno Wallet',
};

export enum AGGREGATOR {
  CASHFREE = 'CASHFREE',
  RAZORPAY = 'RAZORPAY',
}

export const LABEL_BY_AGGREGATOR = {
  [AGGREGATOR.CASHFREE]: 'Cashfree',
  [AGGREGATOR.RAZORPAY]: 'Razorpay',
};
