export enum MODAL_TYPE {
  REVALIDATE = 'REVALIDATE',
  REVALIDATED_SUCCESS = 'REVALIDATED_SUCCESS',
  REVALIDATED_FAILED = 'REVALIDATED_FAILED',

  REVALIDATE_ALL = 'REVALIDATE_ALL',

  EMPTY = '',
}

export const primaryKey = 'id';
