import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import _get from 'lodash/get';

// Utils
import Analytics from 'utils/analytics';
import { getConfigs } from '../utils';

// Services
import * as ReportsService from 'services/reports';

// Constants
import { MENU, LABEL_BY_MENU } from 'constants/menuItems';
import EVENTS from 'constants/events';
import { mockAccountProvider } from '__mocks__/common.mock';
import { MODAL_TYPE, REPORT_LIST } from '../constants';

// Components
import Wrapper from '__tests__/components/Wrapper';
import Modals from '../components/Modals';

// Containers
import Reports from '..';

const { validReportTypes } = getConfigs(
  _get(mockAccountProvider.preferences, 'cashgrams.activated', false),
  [],
);

const mockNavigate = jest.fn();

jest.mock('react-router-dom', () => ({
  ...jest.requireActual('react-router-dom'),
  useNavigate: () => mockNavigate,
}));

jest.mock('utils/analytics', () => ({
  track: jest.fn(),
}));

beforeEach(() => {
  jest.mock('services/reports');

  jest.spyOn(ReportsService, 'getAll').mockImplementation(() =>
    Promise.resolve({
      entries: [
        {
          id: '679466',
          type: 'PO_ACCOUNT',
          reportName: 'Account Statement-17-11-2022',
          size: 316,
          addedOn: '2022-11-17 18:21:07',
          generatedBy: 'Rahul Mallik',
          status: 'READY',
          format: 'CSV',
        },
        {
          id: '679465',
          type: 'TRANSFER',
          reportName: 'Transfer-17-11-2022',
          size: 1145,
          addedOn: '2022-11-17 18:18:53',
          generatedBy: 'Adarsh',
          status: 'READY',
          format: 'CSV',
        },
      ],
      size: 2,
      num: 0,
      total: 2,
    }),
  );

  jest
    .spyOn(ReportsService, 'deleteReport')
    .mockImplementation(() => Promise.resolve({}));

  jest
    .spyOn(ReportsService, 'generateReport')
    .mockImplementation(() => Promise.resolve({}));
});

afterEach(() => {
  jest.resetAllMocks();
  jest.clearAllMocks();
});

describe('In Reports Container', () => {
  test('checks render', async () => {
    render(<Reports />, { wrapper: Wrapper });

    await waitFor(() => {
      expect(ReportsService.getAll).toHaveBeenCalledWith(
        expect.objectContaining({
          reportType: REPORT_LIST.map((report) => report.type),
          size: 10,
        }),
      );

      expect(screen.queryByText('Generated Reports')).toBeInTheDocument();
      expect(screen.queryByText('Generated At')).toBeInTheDocument();
      expect(screen.queryByText('Generated By')).toBeInTheDocument();
      expect(screen.queryByText('Search & Filter')).toBeInTheDocument();
      expect(
        screen.queryByText('Account Statement-17-11-2022'),
      ).toBeInTheDocument();
      expect(screen.queryByText('Rahul Mallik')).toBeInTheDocument();
    });
  });

  test('checks Filters', async () => {
    render(<Reports />, { wrapper: Wrapper });

    await waitFor(() => {
      document.getElementsByClassName('ui inline dropdown')[0].click();

      document
        .getElementsByClassName('visible menu transition')[0]
        .children[1].click();
    });

    expect(Analytics.track).toHaveBeenCalledWith(EVENTS.CHANGE_PAGE_LIMIT, {
      size: '25',
    });

    const searchFilter = screen.queryByText(/Search & Filter/);

    fireEvent.click(screen.queryByText(/Last 7 days/));
    fireEvent.click(screen.queryByText(/Last Month/));

    expect(Analytics.track).toHaveBeenCalledWith(
      EVENTS.DATE_FILTERS,
      expect.objectContaining({
        section: LABEL_BY_MENU[MENU.REPORTS],
      }),
    );

    await waitFor(() => {
      expect(screen.queryByText(/Last Month/)).toBeInTheDocument();
      expect(screen.queryByText(/Last 7 days/)).not.toBeInTheDocument();
    });

    fireEvent.click(searchFilter);

    // await waitFor(() => {
    //   expect(screen.queryByText('Apply')).toBeDisabled();
    //   expect(screen.queryByText('Clear All')).toBeDisabled();
    //   expect(screen.queryByText(/No search available/)).toBeInTheDocument();
    // });

    // const filterOption = document.getElementsByName('TRANSFER')[0];

    // fireEvent.click(filterOption);

    // expect(screen.queryByText('Apply')).not.toBeDisabled();

    // fireEvent.click(screen.queryByText('Apply'));

    // expect(Analytics.track).toHaveBeenCalledWith(
    //   EVENTS.APPLIED_FILTERS,
    //   expect.objectContaining({
    //     section: LABEL_BY_MENU[MENU.REPORTS],
    //     filters: { TRANSFER: true },
    //     search_by: 'transferId',
    //   }),
    // );

    await waitFor(() => {
      expect(screen.queryAllByText(/Ready/).length).toBe(2);
    });

    fireEvent.click(document.getElementsByClassName('cross pointer pl-1')[0]);

    await waitFor(() => {
      expect(screen.getAllByTestId('table-header-cell').length).toBe(6);
      // expect(screen.getAllByTestId('fetching-div').length).toBe(1);
    });
  });

  test('<GenerateReportModal />', async () => {
    render(<Reports />, { wrapper: Wrapper });

    fireEvent.click(await screen.findByText(/Select/));

    expect(screen.queryAllByText(validReportTypes[0].name).length).toBe(2);

    expect(await screen.findByText(/Generate Report/)).toBeDisabled();

    fireEvent.click(await screen.findByText(/Select/));
    fireEvent.click(
      await screen.findByText(new RegExp(validReportTypes[0].description, 'i')),
    );

    const generateReportBtn = await screen.findByText(/Generate Report/);

    expect(generateReportBtn).not.toBeDisabled();

    fireEvent.click(generateReportBtn);

    expect(await screen.findByText(/Choose Fund Sources/)).toBeInTheDocument();
    expect(await screen.findByText(/Choose Columns/)).toBeInTheDocument();
  });

  test('checks Modals render', async () => {
    const setModalType = jest.fn();
    const setFetchCounter = jest.fn();
    const setReportType = jest.fn();

    const configs = {
      labelByStatus: {
        TRANSFER: 'Transfer',
        CASHGRAM: 'Cashgram',
        PO_ACCOUNT: 'Account Statement',
        BENEFICIARY: 'Beneficiary',
        PENDING_TRANSFER: 'Pending Transfer',
        REVERSED_TRANSFER: 'Reversed Transfers',
        PAYOUT_RISK_DETAILS: 'Payout Protect Actioned Transfers',
        RECON_REPORT: 'Recon Report',
      },
      filtersConfig: {
        'Report Type': {
          columns: 2,
          items: [
            'TRANSFER',
            'CASHGRAM',
            'PO_ACCOUNT',
            'BENEFICIARY',
            'PENDING_TRANSFER',
            'REVERSED_TRANSFER',
            'PAYOUT_RISK_DETAILS',
            'RECON_REPORT',
          ],
        },
      },
      validReportTypes: [
        {
          type: 'TRANSFER',
          name: 'Transfer',
          description:
            'View details of Payouts made and details of the Cashgrams that are redeemed for the date range selected.',
          columns: [
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Amount',
              value: 'AMOUNT',
            },
            {
              name: 'Transfer Id',
              value: 'TRANSFER_ID',
            },
            {
              name: 'Reference Id',
              value: 'REFERENCE_ID',
            },
            {
              name: 'Status',
              value: 'STATUS',
            },
            {
              name: 'Beneficiary Name',
              value: 'BENEFICIARY_NAME',
            },
            {
              name: 'Beneficiary Id',
              value: 'BENEFICIARY_ID',
            },
            {
              name: 'Bank Account',
              value: 'BANK_ACCOUNT',
            },
            {
              name: 'IFSC',
              value: 'IFSC',
            },
            {
              name: 'VPA',
              value: 'VPA',
            },
            {
              name: 'Remarks',
              value: 'REMARKS',
            },
            {
              name: 'Bank Reference No',
              value: 'BANK_REF_NO',
            },
            {
              name: 'Service Charge',
              value: 'SERVICE_CHARGE',
            },
            {
              name: 'Service Tax',
              value: 'SERVICE_TAX',
            },
            {
              name: 'Acknowledged',
              value: 'ACKNOWLEDGED',
            },
            {
              name: 'Mode',
              value: 'MODE',
            },
            {
              name: 'Status Code',
              value: 'STATUS_CODE',
            },
            {
              name: 'Status Description',
              value: 'STATUS_DESCRIPTION',
            },
            {
              name: 'Payment Instrument Id',
              value: 'PAYMENT_INSTRUMENT_ID',
            },
            {
              name: 'Processed On',
              value: 'LAST_CHECKED_AT',
            },
            {
              name: 'Added By',
              value: 'ADDED_BY',
            },
          ],
        },
        {
          type: 'CASHGRAM',
          name: 'Cashgram',
          description:
            'View details of Payouts made for the date range selected',
          columns: [
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Cashgram ID',
              value: 'CASHGRAM_ID',
            },
            {
              name: 'Bulk Cashgram ID',
              value: 'BULK_CASHGRAM_ID',
            },
            {
              name: 'Amount',
              value: 'AMOUNT',
            },
            {
              name: 'Bank Account',
              value: 'BANK_ACCOUNT',
            },
            {
              name: 'IFSC',
              value: 'IFSC',
            },
            {
              name: 'VPA',
              value: 'VPA',
            },
            {
              name: 'Service Charge',
              value: 'SERVICE_CHARGE',
            },
            {
              name: 'Service Tax',
              value: 'SERVICE_TAX',
            },
            {
              name: 'Customer Name',
              value: 'CUSTOMER_NAME',
            },
            {
              name: 'Customer Phone',
              value: 'CUSTOMER_PHONE',
            },
            {
              name: 'Customer Email',
              value: 'CUSTOMER_EMAIL',
            },
            {
              name: 'Type',
              value: 'TYPE',
            },
            {
              name: 'Description',
              value: 'DESCRIPTION',
            },
            {
              name: 'Remarks',
              value: 'REMARKS',
            },
            {
              name: 'Link URL',
              value: 'LINK_URL',
            },
            {
              name: 'Status',
              value: 'STATUS',
            },
            {
              name: 'Link Expiry Time',
              value: 'LINK_EXPIRY_TIME',
            },
            {
              name: 'Expiry Reason',
              value: 'LINK_EXPIRY_REASON',
            },
            {
              name: 'Updated On',
              value: 'UPDATED_ON',
            },
            {
              name: 'Redemption Mode',
              value: 'REDEMPTION_MODE',
            },
            {
              name: 'UTR',
              value: 'UTR',
            },
            {
              name: 'Name at Bank',
              value: 'NAME_AT_BANK',
            },
            {
              name: 'Created By',
              value: 'CREATED_BY',
            },
          ],
        },
        {
          type: 'PO_ACCOUNT',
          name: 'Account Statement',
          description:
            'View details of all credits and debits in your Payouts account for the date range selected.',
          columns: [
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Debit/Credit',
              value: 'EVENT',
            },
            {
              name: 'Particulars',
              value: 'EVENT_TYPE',
            },
            {
              name: 'Total Amount (INR)',
              value: 'TOTAL_AMOUNT',
            },
            {
              name: 'Amount (INR)',
              value: 'AMOUNT',
            },
            {
              name: 'Service Charge (INR)',
              value: 'SERVICE_CHARGE',
            },
            {
              name: 'Service Tax (INR)',
              value: 'SERVICE_TAX',
            },
            {
              name: 'Closing Balance (INR)',
              value: 'CLOSING_BALANCE',
            },
            {
              name: 'Event Id',
              value: 'EVENT_ID',
            },
            {
              name: 'Remarks',
              value: 'REMARKS',
            },
          ],
        },
        {
          type: 'BENEFICIARY',
          name: 'Beneficiary',
          description:
            'View details of beneficiaries added in the date range selected.',
          columns: [
            {
              name: 'Beneficiary Id',
              value: 'BENE_ID',
            },
            {
              name: 'Beneficiary Name',
              value: 'BENEFICIARY_NAME',
            },
            {
              name: 'Phone',
              value: 'PHONE',
            },
            {
              name: 'Email',
              value: 'EMAIL',
            },
            {
              name: 'Address',
              value: 'ADDRESS',
            },
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Bank Account',
              value: 'BANK_ACCOUNT',
            },
            {
              name: 'IFSC',
              value: 'IFSC',
            },
            {
              name: 'VPA',
              value: 'VPA',
            },
            {
              name: 'Status',
              value: 'STATUS',
            },
            {
              name: 'Updated On',
              value: 'UPDATED_ON',
            },
            {
              name: 'Reason',
              value: 'REASON',
            },
            {
              name: 'Beneficiary Purpose',
              value: 'BENE_PURPOSE',
            },
          ],
        },
        {
          type: 'PENDING_TRANSFER',
          name: 'Pending Transfer',
          description:
            'View of transfers that are pending with their SLA and due date of completion',
          columns: [
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Amount',
              value: 'AMOUNT',
            },
            {
              name: 'Transfer Id',
              value: 'TRANSFER_ID',
            },
            {
              name: 'Reference Id',
              value: 'REFERENCE_ID',
            },
            {
              name: 'Status',
              value: 'STATUS',
            },
            {
              name: 'Beneficiary Name',
              value: 'BENEFICIARY_NAME',
            },
            {
              name: 'Beneficiary Id',
              value: 'BENEFICIARY_ID',
            },
            {
              name: 'Bank Account',
              value: 'BANK_ACCOUNT',
            },
            {
              name: 'IFSC',
              value: 'IFSC',
            },
            {
              name: 'VPA',
              value: 'VPA',
            },
            {
              name: 'Remarks',
              value: 'REMARKS',
            },
            {
              name: 'Bank Reference No',
              value: 'BANK_REF_NO',
            },
            {
              name: 'Service Charge',
              value: 'SERVICE_CHARGE',
            },
            {
              name: 'Service Tax',
              value: 'SERVICE_TAX',
            },
            {
              name: 'Acknowledged',
              value: 'ACKNOWLEDGED',
            },
            {
              name: 'Mode',
              value: 'MODE',
            },
            {
              name: 'Payment Instrument Id',
              value: 'PAYMENT_INSTRUMENT_ID',
            },
            {
              name: 'SLA',
              value: 'SLA',
            },
            {
              name: 'Due Date',
              value: 'DUE_DATE',
            },
            {
              name: 'Processed On',
              value: 'LAST_CHECKED_AT',
            },
            {
              name: 'Added By',
              value: 'ADDED_BY',
            },
          ],
        },
        {
          type: 'REVERSED_TRANSFER',
          name: 'Reversed Transfers',
          description:
            'View details like date, time and reason of all transfers that are reversed for the date range selected.',
          columns: [
            {
              name: 'Reference Id',
              value: 'REFERENCE_ID',
            },
            {
              name: 'Transfer Id',
              value: 'TRANSFER_ID',
            },
            {
              name: 'Amount',
              value: 'AMOUNT',
            },
            {
              name: 'Reversal Reason',
              value: 'REVERSAL_REASON',
            },
            {
              name: 'Processed On',
              value: 'PROCESSED_ON',
            },
            {
              name: 'Reversed On',
              value: 'REVERSED_ON',
            },
            {
              name: 'Payment Instrument Id',
              value: 'PAYMENT_INSTRUMENT_ID',
            },
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
          ],
        },
        {
          type: 'PAYOUT_RISK_DETAILS',
          name: 'Payout Protect Actioned Transfers',
          description:
            'View details of the transfers which are blocked or flagged by the Payout Protect for the date range selected.',
          columns: [],
        },
        {
          type: 'RECON_REPORT',
          name: 'Recon Report',
          description:
            'Reconciliation of all debits and credits in your Connected fund source and Payouts account for the date range selected',
          columns: [],
        },
      ],
    };

    render(
      <Modals
        configs={configs}
        modalType={MODAL_TYPE.GENERATE}
        setModalType={setModalType}
        setFetchCounter={setFetchCounter}
        setData={jest.fn()}
        selectedRow={{ id: 123, reportName: 'foo bar' }}
        reportType={{
          type: 'TRANSFER',
          name: 'john doe',
          description: 'rainfall',
          columns: [
            { name: 'Added On', value: 'ADDED_ON', checked: true },
            { name: 'Amount', value: 'AMOUNT', checked: true },
          ],
          text: 'foo',
        }}
        setReportType={setReportType}
      />,
      { wrapper: Wrapper },
    );

    await waitFor(
      async () => {
        expect(screen.queryByText('foo Report')).toBeInTheDocument();
        expect(screen.queryByText('Choose Columns')).toBeInTheDocument();

        const submitButton = screen.queryByRole('button', {
          name: 'Generate Report',
        });

        const reportNameInput = screen
          .getByTestId('report-name')
          .querySelector('input');
        expect(reportNameInput).toBeInTheDocument();

        await userEvent.clear(reportNameInput);

        await userEvent.type(reportNameInput, 'foobar');

        expect(reportNameInput.value).toBe('foobar');

        const showAllEl = screen.getByTestId('show-all').querySelector('input');

        await userEvent.click(showAllEl);

        expect(setReportType).toHaveBeenCalled();

        expect(submitButton).not.toBeDisabled();
        expect(submitButton).toHaveClass('ml-4');
        expect(submitButton).toBeInTheDocument();

        fireEvent.click(submitButton);

        expect(ReportsService.generateReport).toHaveBeenCalled();

        // expect(setModalType).toHaveBeenCalled();

        // const cancelButton = screen.queryByText('Cancel');

        // expect(cancelButton).not.toBeDisabled();
        // expect(cancelButton).toBeInTheDocument();

        // fireEvent.click(cancelButton);

        // expect(setModalType).toHaveBeenCalled();
      },
      { timeout: 7000 },
    );
  });

  test('checks Modals render', async () => {
    const setModalType = jest.fn();

    const configs = {
      labelByStatus: {
        TRANSFER: 'Transfer',
        CASHGRAM: 'Cashgram',
        PO_ACCOUNT: 'Account Statement',
        BENEFICIARY: 'Beneficiary',
        PENDING_TRANSFER: 'Pending Transfer',
        REVERSED_TRANSFER: 'Reversed Transfers',
        PAYOUT_RISK_DETAILS: 'Payout Protect Actioned Transfers',
        RECON_REPORT: 'Recon Report',
      },
      filtersConfig: {
        'Report Type': {
          columns: 2,
          items: [
            'TRANSFER',
            'CASHGRAM',
            'PO_ACCOUNT',
            'BENEFICIARY',
            'PENDING_TRANSFER',
            'REVERSED_TRANSFER',
            'PAYOUT_RISK_DETAILS',
            'RECON_REPORT',
          ],
        },
      },
      validReportTypes: [
        {
          type: 'TRANSFER',
          name: 'Transfer',
          description:
            'View details of Payouts made and details of the Cashgrams that are redeemed for the date range selected.',
          columns: [
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Amount',
              value: 'AMOUNT',
            },
            {
              name: 'Transfer Id',
              value: 'TRANSFER_ID',
            },
            {
              name: 'Reference Id',
              value: 'REFERENCE_ID',
            },
            {
              name: 'Status',
              value: 'STATUS',
            },
            {
              name: 'Beneficiary Name',
              value: 'BENEFICIARY_NAME',
            },
            {
              name: 'Beneficiary Id',
              value: 'BENEFICIARY_ID',
            },
            {
              name: 'Bank Account',
              value: 'BANK_ACCOUNT',
            },
            {
              name: 'IFSC',
              value: 'IFSC',
            },
            {
              name: 'VPA',
              value: 'VPA',
            },
            {
              name: 'Remarks',
              value: 'REMARKS',
            },
            {
              name: 'Bank Reference No',
              value: 'BANK_REF_NO',
            },
            {
              name: 'Service Charge',
              value: 'SERVICE_CHARGE',
            },
            {
              name: 'Service Tax',
              value: 'SERVICE_TAX',
            },
            {
              name: 'Acknowledged',
              value: 'ACKNOWLEDGED',
            },
            {
              name: 'Mode',
              value: 'MODE',
            },
            {
              name: 'Status Code',
              value: 'STATUS_CODE',
            },
            {
              name: 'Status Description',
              value: 'STATUS_DESCRIPTION',
            },
            {
              name: 'Payment Instrument Id',
              value: 'PAYMENT_INSTRUMENT_ID',
            },
            {
              name: 'Processed On',
              value: 'LAST_CHECKED_AT',
            },
            {
              name: 'Added By',
              value: 'ADDED_BY',
            },
          ],
        },
        {
          type: 'CASHGRAM',
          name: 'Cashgram',
          description:
            'View details of Payouts made for the date range selected',
          columns: [
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Cashgram ID',
              value: 'CASHGRAM_ID',
            },
            {
              name: 'Bulk Cashgram ID',
              value: 'BULK_CASHGRAM_ID',
            },
            {
              name: 'Amount',
              value: 'AMOUNT',
            },
            {
              name: 'Bank Account',
              value: 'BANK_ACCOUNT',
            },
            {
              name: 'IFSC',
              value: 'IFSC',
            },
            {
              name: 'VPA',
              value: 'VPA',
            },
            {
              name: 'Service Charge',
              value: 'SERVICE_CHARGE',
            },
            {
              name: 'Service Tax',
              value: 'SERVICE_TAX',
            },
            {
              name: 'Customer Name',
              value: 'CUSTOMER_NAME',
            },
            {
              name: 'Customer Phone',
              value: 'CUSTOMER_PHONE',
            },
            {
              name: 'Customer Email',
              value: 'CUSTOMER_EMAIL',
            },
            {
              name: 'Type',
              value: 'TYPE',
            },
            {
              name: 'Description',
              value: 'DESCRIPTION',
            },
            {
              name: 'Remarks',
              value: 'REMARKS',
            },
            {
              name: 'Link URL',
              value: 'LINK_URL',
            },
            {
              name: 'Status',
              value: 'STATUS',
            },
            {
              name: 'Link Expiry Time',
              value: 'LINK_EXPIRY_TIME',
            },
            {
              name: 'Expiry Reason',
              value: 'LINK_EXPIRY_REASON',
            },
            {
              name: 'Updated On',
              value: 'UPDATED_ON',
            },
            {
              name: 'Redemption Mode',
              value: 'REDEMPTION_MODE',
            },
            {
              name: 'UTR',
              value: 'UTR',
            },
            {
              name: 'Name at Bank',
              value: 'NAME_AT_BANK',
            },
            {
              name: 'Created By',
              value: 'CREATED_BY',
            },
          ],
        },
        {
          type: 'PO_ACCOUNT',
          name: 'Account Statement',
          description:
            'View details of all credits and debits in your Payouts account for the date range selected.',
          columns: [
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Debit/Credit',
              value: 'EVENT',
            },
            {
              name: 'Particulars',
              value: 'EVENT_TYPE',
            },
            {
              name: 'Total Amount (INR)',
              value: 'TOTAL_AMOUNT',
            },
            {
              name: 'Amount (INR)',
              value: 'AMOUNT',
            },
            {
              name: 'Service Charge (INR)',
              value: 'SERVICE_CHARGE',
            },
            {
              name: 'Service Tax (INR)',
              value: 'SERVICE_TAX',
            },
            {
              name: 'Closing Balance (INR)',
              value: 'CLOSING_BALANCE',
            },
            {
              name: 'Event Id',
              value: 'EVENT_ID',
            },
            {
              name: 'Remarks',
              value: 'REMARKS',
            },
          ],
        },
        {
          type: 'BENEFICIARY',
          name: 'Beneficiary',
          description:
            'View details of beneficiaries added in the date range selected.',
          columns: [
            {
              name: 'Beneficiary Id',
              value: 'BENE_ID',
            },
            {
              name: 'Beneficiary Name',
              value: 'BENEFICIARY_NAME',
            },
            {
              name: 'Phone',
              value: 'PHONE',
            },
            {
              name: 'Email',
              value: 'EMAIL',
            },
            {
              name: 'Address',
              value: 'ADDRESS',
            },
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Bank Account',
              value: 'BANK_ACCOUNT',
            },
            {
              name: 'IFSC',
              value: 'IFSC',
            },
            {
              name: 'VPA',
              value: 'VPA',
            },
            {
              name: 'Status',
              value: 'STATUS',
            },
            {
              name: 'Updated On',
              value: 'UPDATED_ON',
            },
            {
              name: 'Reason',
              value: 'REASON',
            },
            {
              name: 'Beneficiary Purpose',
              value: 'BENE_PURPOSE',
            },
          ],
        },
        {
          type: 'PENDING_TRANSFER',
          name: 'Pending Transfer',
          description:
            'View of transfers that are pending with their SLA and due date of completion',
          columns: [
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
            {
              name: 'Amount',
              value: 'AMOUNT',
            },
            {
              name: 'Transfer Id',
              value: 'TRANSFER_ID',
            },
            {
              name: 'Reference Id',
              value: 'REFERENCE_ID',
            },
            {
              name: 'Status',
              value: 'STATUS',
            },
            {
              name: 'Beneficiary Name',
              value: 'BENEFICIARY_NAME',
            },
            {
              name: 'Beneficiary Id',
              value: 'BENEFICIARY_ID',
            },
            {
              name: 'Bank Account',
              value: 'BANK_ACCOUNT',
            },
            {
              name: 'IFSC',
              value: 'IFSC',
            },
            {
              name: 'VPA',
              value: 'VPA',
            },
            {
              name: 'Remarks',
              value: 'REMARKS',
            },
            {
              name: 'Bank Reference No',
              value: 'BANK_REF_NO',
            },
            {
              name: 'Service Charge',
              value: 'SERVICE_CHARGE',
            },
            {
              name: 'Service Tax',
              value: 'SERVICE_TAX',
            },
            {
              name: 'Acknowledged',
              value: 'ACKNOWLEDGED',
            },
            {
              name: 'Mode',
              value: 'MODE',
            },
            {
              name: 'Payment Instrument Id',
              value: 'PAYMENT_INSTRUMENT_ID',
            },
            {
              name: 'SLA',
              value: 'SLA',
            },
            {
              name: 'Due Date',
              value: 'DUE_DATE',
            },
            {
              name: 'Processed On',
              value: 'LAST_CHECKED_AT',
            },
            {
              name: 'Added By',
              value: 'ADDED_BY',
            },
          ],
        },
        {
          type: 'REVERSED_TRANSFER',
          name: 'Reversed Transfers',
          description:
            'View details like date, time and reason of all transfers that are reversed for the date range selected.',
          columns: [
            {
              name: 'Reference Id',
              value: 'REFERENCE_ID',
            },
            {
              name: 'Transfer Id',
              value: 'TRANSFER_ID',
            },
            {
              name: 'Amount',
              value: 'AMOUNT',
            },
            {
              name: 'Reversal Reason',
              value: 'REVERSAL_REASON',
            },
            {
              name: 'Processed On',
              value: 'PROCESSED_ON',
            },
            {
              name: 'Reversed On',
              value: 'REVERSED_ON',
            },
            {
              name: 'Payment Instrument Id',
              value: 'PAYMENT_INSTRUMENT_ID',
            },
            {
              name: 'Added On',
              value: 'ADDED_ON',
            },
          ],
        },
        {
          type: 'PAYOUT_RISK_DETAILS',
          name: 'Payout Protect Actioned Transfers',
          description:
            'View details of the transfers which are blocked or flagged by the Payout Protect for the date range selected.',
          columns: [],
        },
        {
          type: 'RECON_REPORT',
          name: 'Recon Report',
          description:
            'Reconciliation of all debits and credits in your Connected fund source and Payouts account for the date range selected',
          columns: [],
        },
      ],
    };

    render(
      <Modals
        configs={configs}
        modalType={MODAL_TYPE.DELETE}
        setModalType={setModalType}
        setFetchCounter={jest.fn()}
        setData={jest.fn()}
        selectedRow={{ id: 123, reportName: 'foo bar' }}
        reportType={{
          type: 'TRANSFER',
          name: 'john doe',
          description: 'rainfall',
          columns: [],
        }}
        setReportType={jest.fn()}
      />,
      { wrapper: Wrapper },
    );

    await waitFor(() => {
      expect(screen.queryByText('Delete Report')).toBeInTheDocument();

      expect(
        screen.queryByText(
          'Are you sure you want to delete the foo bar report?',
        ),
      ).toBeInTheDocument();

      const submitButton = screen.queryByRole('button', {
        name: 'Delete',
      });

      expect(submitButton).toHaveClass('ml-2');
      expect(submitButton).toBeInTheDocument();

      // userEvent.click(submitButton);

      // expect(ReportsService.deleteReport).toHaveBeenCalledWith(123);
      // expect(setModalType).toHaveBeenCalled();

      // const cancelButton = screen.queryByText('Cancel');

      // expect(cancelButton).not.toBeDisabled();
      // expect(cancelButton).toBeInTheDocument();

      // userEvent.click(cancelButton);

      // expect(setModalType).toHaveBeenCalled();
    });
  });

  test('checks Row click', async () => {
    render(<Reports />, { wrapper: Wrapper });

    await waitFor(() => {
      const firstRow = screen.getAllByTestId('table-row')[0];
      fireEvent.click(firstRow);
    });

    expect(mockNavigate).not.toHaveBeenCalled();
  });
});
