import React from 'react';
import { MemoryRouter } from 'react-router-dom';
import ShallowRenderer from 'react-test-renderer/shallow';
import { render, screen, waitFor } from '@testing-library/react';
import { Theme } from '@cashfree-intl/coherent';

// Providers
import { MerchantContext } from 'providers/MerchantProvider';
import { AccountContext } from 'providers/AccountProvider';

import { TwoFactorProvider } from 'pages/Developers/providers';

// Mocks
import {
  mockAccountProvider,
  mockMerchantProvider,
} from '__mocks__/common.mock';

// Action Types
import COMMON_ACTION_TYPE from 'actionTypes/common';

// Pages
import Developers from '..';

// Reducers
import { reducers, initialState } from '../reducers';

const renderer = new ShallowRenderer();

// eslint-disable-next-line react/prop-types
const CustomWrapper = ({ children }) => (
  <MemoryRouter initialEntries={[{ pathname: '/api-keys' }]}>
    <Theme>
      <MerchantContext.Provider value={mockMerchantProvider}>
        <AccountContext.Provider value={mockAccountProvider}>
          <TwoFactorProvider>{children}</TwoFactorProvider>
        </AccountContext.Provider>
      </MerchantContext.Provider>
    </Theme>
  </MemoryRouter>
);

describe('In Developers page', () => {
  test('shallow render & match the snapshot', () => {
    renderer.render(
      <CustomWrapper>
        <Developers />
      </CustomWrapper>,
    );

    const output = renderer.getRenderOutput();
    expect(output).toMatchSnapshot();
  });

  test('checks Developers', async () => {
    render(<Developers />, { wrapper: CustomWrapper });

    await waitFor(() => {
      expect(screen.queryByText('Generated At')).toBeInTheDocument();
      expect(screen.queryByText('Generated By')).toBeInTheDocument();
      expect(screen.queryByText('Client ID')).toBeInTheDocument();
      expect(screen.queryByText('Client Secret')).toBeInTheDocument();
      expect(screen.queryByText('No data found!')).toBeInTheDocument();
      expect(screen.queryByText('View History')).toBeInTheDocument();
      expect(screen.queryByText('Generate API Keys')).toBeInTheDocument();
    });
  });

  test('reducers()', () => {
    expect(reducers({}, { type: 'RESET' })).toStrictEqual(initialState);

    expect(
      reducers(
        {},
        {
          type: COMMON_ACTION_TYPE.SET_DATA,
          payload: 'foo',
        },
      ),
    ).toStrictEqual({
      selected2FA: 'foo',
    });

    expect(
      reducers(
        {},
        {
          type: 'SOMETHING',
          payload: 'foo',
        },
      ),
    ).toBeUndefined();
  });
});
