export enum MODAL_TYPE {
  BLOCK = 'BLOCK',
  APPROVE = 'APPROVE',
  EMPTY = '',
}

export const FLAGGED_REASONS = [
  'INSIDE_BLACKOUT_WINDOW',
  'VELOCITY_CHECK_FAILED',
  'TRANSFER_LIMIT_BREACH',
  'BENE_BLACKLISTED',
  'ANOMALY_DETECTION',
];

export enum STATUS_MAPPING {
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  REJECTED = 'REJECTED',
  MANUALLY_ALLOWED = 'MANUALLY_ALLOWED',
}
