import React from 'react';
import { Space, toast, EllipsisPopup } from '@cashfree-intl/coherent';
import _isEmpty from 'lodash/isEmpty';
import moment from 'moment';
import _get from 'lodash/get';

// Components
import Icon from 'components/Icon';
import StatusLabel from 'components/StatusLabel';
import CanWrite from 'components/CanWrite';

// Constants
import {
  ACTION_TYPES,
  VALID_REPORT_TYPES as DEFAULT_FILTERS,
  LABEL_BY_TYPE,
  FILE_EXTENSIONS,
} from './constants';
import { FORMATS } from 'constants/date';

// Helpers
import { formattedDate } from 'helpers/common';

// Utils
import { getSizeText } from 'utils/common';

const actions = [
  {
    key: 1,
    text: 'Download',
    value: ACTION_TYPES.DOWNLOAD,
    image: props => <Icon name="download" {...props} />,
  },
  {
    key: 2,
    text: 'Delete',
    value: ACTION_TYPES.DELETE,
    image: props => <Icon name="delete" {...props} />,
    type: 'danger',
  },
];

export const getQuery = (filters, dateValue, limit) => {
  const status = _isEmpty(filters) ? DEFAULT_FILTERS : Object.keys(filters);

  const queryObj = {
    reportType: status,
    size: limit,
  };

  if (dateValue.range) {
    const [startDate, endDate] = dateValue.range;

    queryObj.startDate = formattedDate(startDate, FORMATS.START_DATE);
    queryObj.endDate = formattedDate(endDate, FORMATS.END_DATE);
  }

  return queryObj;
};

export const getFormattedData = (handleDownload, handleDelete) => [
  {
    accessorKey: 'type',
    header: 'Type',
    cell: ({ type }) => LABEL_BY_TYPE[type] || '–',
  },
  {
    accessorKey: 'reportName',
    header: 'Report Name',
    cell: row => _get(row, 'reportName', '-'),
  },
  {
    accessorKey: 'size',
    header: 'Size',
    align: 'right',
    cell: ({ size }) => getSizeText(size),
  },
  {
    accessorKey: 'generatedAt',
    header: 'Generated At',
    cell: ({ addedOn }) => moment.utc(addedOn).format(FORMATS.TIMESTAMP),
  },
  {
    accessorKey: 'generatedBy',
    header: 'Generated By',
    cell: row => _get(row, 'generatedBy', '-'),
  },
  {
    accessorKey: 'action',
    header: '',
    align: 'right',
    cell: row => {
      if (!['READY', 'COMPLETED'].includes(row.status)) {
        return (
          <div>
            <StatusLabel className="mr-2">{row.status}</StatusLabel>
          </div>
        );
      }

      const isReportEmpty = row.size === 0;

      const onItemClick = (_, itemSelected) => {
        switch (itemSelected) {
          case ACTION_TYPES.DOWNLOAD:
            if (!isReportEmpty) {
              handleDownload(row);
              return;
            }
            toast.warn('No records found for the selected period');
            return;

          case ACTION_TYPES.DELETE:
            handleDelete(row);
        }
      };

      return (
        <CanWrite code={23002}>
          <Space justifyContent="flex-end" className="pr-2">
            <EllipsisPopup menuItems={actions} onClick={onItemClick} />
          </Space>
        </CanWrite>
      );
    },
  },
];
