// Constants
import { USER_TYPE } from 'constants/common';

export const mockMerchantProvider = {
  merchantSettings: {
    enableConnectedWallet: false,
    enableMerchantAPIKeyAddition: false,
  },
  merchantDetails: {
    authType: 'OTP',
    userType: USER_TYPE.MERCHANT_OWNER,
    cfProductStatus: {
      CAC: 'APPROVED',
      CES: 'APPROVED',
      CSP: 'APPROVED',
      EPOS: 'APPROVED',
      PG: 'APPROVED',
    },
  },
  accountList: [
    {
      accountId: 7447,
      accountType: 'PAYOUT_CURRENT',
      accountName: 'Raj Nandan Sharma',
      rechargeAccount: '70707010J15S',
      availableBalance: '16.29',
    },
  ],
  restrictionCodes: [],
  featureFlags: {},
};

export const mockAccountProvider = {
  accountInfo: {
    name: 'Raj Nandan Sharma',
    phone: '1234567890',
    email: 'kisley.shirish+cfmain@cashfree.com',
    state: 'Bengaluru',
    address: 'Koramangala',
    city: 'Ranchi',
    bankAccount: '111111111111',
    ifsc: 'ICIC0003439',
    accountHolder: 'sdfsdf',
    isActive: '1',
    bankname: 'ICICI',
  },
  preferences: {
    isConnected: false,
    selfWithdrawal: true,
    quickTransfer: true,
    webhookVersion: '4-9-2020',
    transfers: {
      individual: '0',
      batch: '1',
      upload: true,
    },
    cashgrams: {
      activated: true,
      individual: '1',
      batch: '1',
      upload: true,
      verify: true,
    },
    bav: {
      activated: {
        ServiceName: 'BANKDETAILS_VALIDATION',
        Rate: '1.1',
        VariableAmount: 0,
      },
      batch: '1',
      upload: true,
    },
    pan: {
      activated: {
        ServiceName: 'PANDETAILS_VERIFICATION',
        Rate: '1.5',
        VariableAmount: 1,
      },
      upload: true,
    },
    beneficiaries: {
      purpose: {
        others: true,
        corpCC: true,
      },
    },
    merchantPreferences: {
      DISABLE_NEFT_RETRY: true,
      DISABLE_RETRY_TRANSFER_PAYOUT: true,
      MAX_LOW_BALANCE_QUEUEING_TIME: 100,
      PHONE_MODE_NAME_MATCH_THRESHOLD: 50,
      TRANSFERS_MAX_RETRY_TIME: 20,
      CASHGRAM_TRANSFER_ENABLED: true,
      CASHGRAM_MERCHANT_NAME: 'Dream11',
      CASHGRAM_REDIRECT_URL: 'https://whydowehope.gov.in',
      CASHGRAM_SUPPORT_MAIL: 'example@cashfree.com',
      CASHGRAM_VALIDATION_BV_RATE: 30,
      CASHGRAM_VALIDATION_CREATION_RATE: 30,
      AMAZON_UPI_BENE_NOTIFY_MEDIUM: 30,
      INCIDENT_WEBHOOK_ENABLED: true,
      BULK_UPLOADS_BENE: false,
    },
    modeByName: {
      imps: {
        ID: 149262,
        IsQueued: 0,
        ModeID: 9,
        Mode: 'imps',
        Status: '',
      },
      neft: {
        ID: 149263,
        IsQueued: 0,
        ModeID: 10,
        Mode: 'neft',
        Status: '',
      },
      upi: {
        ID: 149264,
        IsQueued: 0,
        ModeID: 3,
        Mode: 'upi',
        Status: '',
      },
      amazonpay: {
        ID: 150842,
        IsQueued: 0,
        ModeID: 5,
        Mode: 'amazonpay',
        Status: '',
      },
      phone: {
        ID: 151498,
        IsQueued: 0,
        ModeID: 12,
        Mode: 'phone',
        Status: '',
      },
      AMZN_UPI: {
        ID: 184060,
        IsQueued: 0,
        ModeID: 13,
        Mode: 'AMZN_UPI',
        Status: '',
      },
      card: {
        ID: 184181,
        IsQueued: 0,
        ModeID: 4,
        Mode: 'card',
        Status: '',
      },
      creditcard: {
        ID: 184182,
        IsQueued: 0,
        ModeID: 6,
        Mode: 'creditcard',
        Status: '',
      },
    },
  },
  accountConfig: {
    MerchantName: 'XXXX',
    MerchantEmail: 'example@example.com',
  },
  slabCharges: [],
  permissionCodes: [],
  yesBusinessType: 'Partnership',
};

export const mockDetailsProvider = {
  details: {
    accountId: 0,
    fsType: 'PAYOUT_NODAL',
    fsDisplayType: 'CREDIT_CARD',
    fsDescription: null,
    accountHolderName: '',
    cfCredId: 0,
    cfBankId: 7,
    bankAccount: '',
    ifsc: '',
    sweepAccount: 0,
    isActive: 0,
    isPayoutWallet: true,
    isDefault: false,
    isMainAccount: false,
    walletCode: '',
    addedOn: '2022-09-14T15:24:45+05:30',
    displayName: 'CC-Nagaraj-Temp10',
    virtualAccount: 'john@987',
    status: 'ACTIVE',
    connBankName: '',
    merchantName: 'Logesh',
    connectDetails: {
      cardHolderName: '',
      cardNetwork: 'mastercard',
      cardNumber: 'XXXXXXXXXXXX2052',
      channel: '',
    },
    fundSourceId: 39240,
    paymentInstrumentId: 'CREDIT_CARD_102_c5fecd2',
    cfBankName: '',
    fsBalance: {
      balance: '19.44',
      availableBalance: '19.44',
      fundsOnHold: '0',
      overdraft: '0',
      lastUpdated: '',
    },
  },
  showServiceCharges: true,
};

export const mockFundSources = [
  {
    fundSourceId: 14576,
    fsType: 'CONNECTED',
    fsDisplayType: 'BANK_ACCOUNT',
    paymentInstrumentId: 'RBL_CONNECTED',
    displayName: 'ICICI-124',
    fsDescription: 'Rbl Connected payment instrument',
    accountHolderName: 'CASHFREE PAYMENTS PRIVATE LIMITED',
    isDefault: true,
    isPayoutWallet: false,
    isMainAccount: false,
    bankAccount: '234005000876',
    ifsc: 'ICIC0002340',
    cfBankId: 0,
    cfBankName: 'RBL_CONNECTED',
    connBankName: 'RBL_CONNECTED',
    cfBankType: '',
    cfCredId: 238,
    cfGatewayId: 46,
    preferences: {
      FUND_SOURCE_WEIGHTAGE: '0',
    },
    fsBalance: {
      balance: '0',
      availableBalance: '0',
      fundsOnHold: '0',
      overdraft: '0',
      lastUpdated: '',
    },
    supportedModes: ['banktransfer'],
    status: 'ACTIVE',
    addedOn: '2022-04-12T00:00:00+05:30',
  },
  {
    fundSourceId: 39240,
    fsType: 'PAYOUT_NODAL',
    fsDisplayType: 'CREDIT_CARD',
    paymentInstrumentId: 'CREDIT_CARD_102_c5fecd2',
    displayName: 'CC-Nagaraj-Temp10',
    fsDescription: null,
    accountHolderName: '',
    isDefault: false,
    isPayoutWallet: true,
    isMainAccount: false,
    bankAccount: '',
    ifsc: '',
    cfBankId: 7,
    cfBankName: 'HDFC',
    connBankName: '',
    cfBankType: 'CURRENT',
    cfCredId: 0,
    cfGatewayId: 0,
    preferences: {
      FUND_SOURCE_WEIGHTAGE: '0',
    },
    fsBalance: {
      balance: '19.44',
      availableBalance: '19.44',
      fundsOnHold: '0',
      overdraft: '0',
      lastUpdated: '2022-12-01 14:43:23',
    },
    supportedModes: [
      'banktransfer',
      'amazonpay',
      'upi',
      'card',
      'creditcard',
      'creditcardUpi',
      'imps',
      'neft',
      'opgsp',
    ],
    status: 'ACTIVE',
    addedOn: '2022-09-14T15:24:45+05:30',
  },
];

export const mockEscrowProvider = [
  {
    fundSourceId: 729954,
    fsType: 'CONNECTED',
    fsDisplayType: 'CONNECTED_WALLET',
    paymentInstrumentId: 'YES_b319d91',
    displayName: 'Test_priyanka',
    fsDescription: null,
    accountHolderName: 'john doe',
    isDefault: false,
    isPayoutWallet: false,
    isMainAccount: false,
    bankAccount: '026291800000092\n',
    ifsc: 'YESB0000262',
    cfBankId: 8,
    cfBankName: 'YES_CONNECTED',
    connBankName: 'YES_CONNECTED',
    cfBankType: 'CONNECTED',
    cfCredId: 18658,
    cfGatewayId: 14,
    preferences: [
      {
        property: 'FUND_SOURCE_WEIGHTAGE',
        value: '0',
      },
    ],
    fsBalance: {
      balance: '60',
      availableBalance: '60',
      fundsOnHold: '0',
      overdraft: '0',
      lastUpdated: '2024-07-02 12:14:57',
    },
    supportedModes: ['banktransfer', 'creditcard', 'ccPhone'],
    status: 'ACTIVE',
    addedOn: '2024-06-26T13:31:26+05:30',
    product: 'ONE_ESCROW',
    currency: 'INR',
    modeRates: [],
    fsSlabCharges: [],
    virtualAccount: '97654104VZJ',
  },
  {
    fundSourceId: 729956,
    fsType: 'CONNECTED',
    fsDisplayType: 'CONNECTED_WALLET',
    paymentInstrumentId: 'YES_CONNECTED_1_0927n73',
    displayName: 'Test_surjeet',
    fsDescription: null,
    accountHolderName: 'john doe',
    isDefault: false,
    isPayoutWallet: false,
    isMainAccount: false,
    bankAccount: '026291800000092\n',
    ifsc: 'YESB0000262',
    cfBankId: 8,
    cfBankName: 'YES_CONNECTED',
    connBankName: 'YES_CONNECTED',
    cfBankType: 'CONNECTED',
    cfCredId: 18658,
    cfGatewayId: 14,
    preferences: [
      {
        property: 'FUND_SOURCE_WEIGHTAGE',
        value: '0',
      },
    ],
    fsBalance: {
      balance: '200',
      availableBalance: '200',
      fundsOnHold: '0',
      overdraft: '0',
      lastUpdated: '2024-07-02 12:14:57',
    },
    supportedModes: ['banktransfer', 'creditcard', 'ccPhone'],
    status: 'DEACTIVATED',
    addedOn: '2024-06-26T13:31:26+05:30',
    product: 'ONE_ESCROW',
    currency: 'INR',
    modeRates: [],
    fsSlabCharges: [],
    virtualAccount: '87654104VZJ',
  },
  {
    fundSourceId: 729955,
    fsType: 'CONNECTED',
    fsDisplayType: 'CONNECTED_WALLET',
    paymentInstrumentId: 'YES_CONNECTED_1_832746b',
    displayName: 'hhhyu',
    fsDescription: null,
    accountHolderName: 'john doe',
    isDefault: false,
    isPayoutWallet: false,
    isMainAccount: false,
    bankAccount: '026291800000092\n',
    ifsc: 'YESB0000262',
    cfBankId: 8,
    cfBankName: 'YES_CONNECTED',
    connBankName: 'YES_CONNECTED',
    cfBankType: 'CONNECTED',
    cfCredId: 18658,
    cfGatewayId: 14,
    preferences: [
      {
        property: 'FUND_SOURCE_WEIGHTAGE',
        value: '0',
      },
    ],
    fsBalance: {
      balance: '100',
      availableBalance: '100',
      fundsOnHold: '0',
      overdraft: '0',
      lastUpdated: '2024-07-02 12:14:57',
    },
    supportedModes: ['banktransfer', 'creditcard', 'ccPhone'],
    status: 'ACTIVE',
    addedOn: '2024-06-26T13:31:26+05:30',
    product: 'ONE_ESCROW',
    currency: 'INR',
    modeRates: [],
    fsSlabCharges: [],
    virtualAccount: '97654104XXX',
  },
  {
    fundSourceId: 715828,
    fsType: 'CONNECTED',
    fsDisplayType: 'CONNECTED_WALLET',
    paymentInstrumentId: 'YES_CONNECTED_1_a53db9a',
    displayName: 'erer',
    fsDescription: null,
    accountHolderName: 'john doe',
    isDefault: false,
    isPayoutWallet: false,
    isMainAccount: false,
    bankAccount: '026291800000092\n',
    ifsc: 'YESB0000262',
    cfBankId: 8,
    cfBankName: 'YES_CONNECTED',
    connBankName: 'YES_CONNECTED',
    cfBankType: 'CONNECTED',
    cfCredId: 18527,
    cfGatewayId: 14,
    preferences: [
      {
        property: 'FUND_SOURCE_WEIGHTAGE',
        value: '0',
      },
    ],
    fsBalance: {
      balance: '1503',
      availableBalance: '1503',
      fundsOnHold: '0',
      overdraft: '0',
      lastUpdated: '2024-07-02 12:14:57',
    },
    supportedModes: ['banktransfer', 'creditcard', 'ccPhone'],
    status: 'ACTIVE',
    addedOn: '2024-06-07T15:51:39+05:30',
    product: 'ONE_ESCROW',
    currency: 'INR',
    modeRates: [],
    fsSlabCharges: [
      {
        id: 151498,
        modeId: 12,
        lBound: 100,
        uBound: 200,
        charge: 5,
      },
      {
        id: 184060,
        modeId: 13,
        lBound: 300,
        uBound: 400,
        charge: 10,
      },
    ],
    virtualAccount: '97654107BWT',
  },
];
