export const merchantProviderMock = {
  activationDetails: {
    authType: 'OTP',
    userType: 'MERCHANT_OWNER',
    CAC: 'APPROVED',
    CES: 'APPROVED',
    CSP: 'APPROVED',
    EPOS: 'APPROVED',
    PG: 'APPROVED',
  },
  accountList: [
    {
      accountId: 7447,
      accountType: 'PAYOUT_CURRENT',
      accountName: 'Raj Nandan Sharma',
      rechargeAccount: '70707010J15S',
      availableBalance: '16.29',
    },
    {
      accountId: 7449,
      accountType: 'CONNECTED_ACCOUNT',
      accountName: 'Naman',
      rechargeAccount: '70707010J143',
      availableBalance: '546.23',
    },
  ],
  permissionCodes: [21008, 21504],
};

export const accountProviderMock = {
  accountInfo: {
    name: 'Raj Nandan Sharma',
    phone: '1234567890',
    email: 'kisley.shirish+cfmain@cashfree.com',
    state: 'Bengaluru',
    address: 'Koramangala',
    city: 'Ranchi',
    bankAccount: '111111111111',
    ifsc: 'ICIC0003439',
    accountHolder: 'sdfsdf',
    isActive: '1',
    bankname: 'ICICI',
  },
  preferences: {
    isConnected: false,
    selfWithdrawal: true,
    quickTransfer: true,
    activated: {
      bav: {
        ServiceName: 'BANKDETAILS_VALIDATION',
        Rate: '1.1',
        VariableAmount: 0,
      },
      pan: {
        ServiceName: 'PANDETAILS_VERIFICATION',
        Rate: '1.5',
        VariableAmount: 1,
      },
      upi: true,
      okyc: true,
      gstIn: true,
      ifsc: true,
      'upi-mobile': true,
      'aadhaar-ocr': true,
      'bav-rpd': true,
    },
    bav: {
      batch: '1',
      upload: true,
    },
    upi: {
      upload: true,
    },
    pan: {
      upload: true,
    },
    beneficiaries: {
      upload: true,
    },
    forms: {
      upload: true,
    },
  },
  fundSource: {
    fundSourceId: 102,
    paymentInstrumentId: 'CASHFREE_1',
    description: 'This ismain account',
    type: 'PAYOUT_CURRENT',
    bankName: 'ICICI',
    isWallet: true,
    accountName: '',
    supportedModes: [
      'banktransfer',
      'amazonpay',
      'upi',
      'card',
      'creditcard',
      'imps',
      'neft',
      'opgsp',
    ],
  },
  freeCreditRates: {
    test: '1.52',
    test2: '1',
    CIN_VERIFICATION: '1.2',
    BAV_PENNILESS: '1',
    BAV_ONEPAISA: '1.1',
    CREDIT_SCOREV: '20',
    BANKDETAILS_VALIDATION: '3',
    UPIDETAILS_VALIDATION: '1.2',
    PANDETAILS_VERIFICATION: '2',
    AADHAAR_VERIFICATION: '1.2',
    GSTIN_VERIFICATION: '1',
    AADHAAR_OFFLINE_VERIFICATION: '1',
    OFFLINE_AADHAAR_VERIFICATION: '1.3',
    AADHAAR_OCR_V: '2',
    PAN_OCR_V: '1',
    CREDIT_SCORE_V: '50',
    REVERSE_PENNY_DROP_V: '2',
    IFSC_VERIFICATION: '1.5',
  },
  fundSourceDetails: {
    fundSourceId: 516730,
    fsType: 'PAYOUT_NODAL',
    fsDisplayType: 'CF_WALLET',
    paymentInstrumentId: 'VRS_352818',
    displayName: 'VRS_352818',
    fsDescription: 'Dedicated VRS wallet',
    accountHolderName: 'Business Name',
    isDefault: false,
    isPayoutWallet: true,
    isMainAccount: true,
    bankAccount: '12345678',
    ifsc: 'CASH0FREE01',
    cfBankId: 4,
    cfBankName: 'YES',
    connBankName: '',
    cfBankType: 'CURRENT',
    cfCredId: 0,
    cfGatewayId: 0,
    preferences: [
      {
        property: 'FUND_SOURCE_WEIGHTAGE',
        value: '0',
      },
    ],
    fsBalance: {
      balance: '20000',
      availableBalance: '20000',
      fundsOnHold: '0',
      overdraft: '0',
      lastUpdated: '2023-09-28 22:55:02',
    },
    supportedModes: [
      'banktransfer',
      'amazonpay',
      'upi',
      'card',
      'creditcard',
      'creditcardUpi',
      'imps',
      'neft',
      'opgsp',
    ],
    status: 'ACTIVE',
    addedOn: '2023-09-28T21:46:28+05:30',
    product: 'VRS',
  },
};
