import _pick from 'lodash/pick';

// Constants
import { LABEL_BY_STATUS } from 'constants/status';

export const SUB_STAGES_BY_STAGE = {
  DETAILS_FILLED_BY_MERCHANT: ['NEW_ETB_LEAD_CREATED', 'NEW_NTB_LEAD_CREATED'],
  WORK_ORDER_RECEIVED_TO_BO: ['NEW_ETB_LEAD_CREATED', 'NEW_NTB_LEAD_CREATED'],
  LEAD_SENT_TO_BANK: [
    'LEAD_SENT_TO_BANK_FOR_APPROVAL',
    'LEAD_RESHARED_WITH_SALES',
  ],
  BANK_VALIDATION: [
    'API_FORM_SHARED_BY_BANK_TO_MERCHANT',
    'CALL_DONE_BW_MERCHANT_AND_BANK',
    'ESCALATED_TO_BA',
  ],
  FORM_FILLING: [
    'SUBMIT_API_FORMS_TO_BANK',
    'ESCALATE_TO_SALES_TO_EXPEDITE',
    'API_FORMS_SUBMITTED_TO_BANK_FOR_REVIEW',
    'MERCHANT_TO_SUBMIT_UPDATED_API_FORMS_TO_BANK',
    'ESCALATE_TO_SALES_TO_EXPEDITE_FOR_UPDATED_FORMS',
  ],
  BANK_COMPLIANCE_REVIEW: [
    'FORMS_ACCEPTED_BY_THE_BANK',
    'ESCALATED_TO_BA_FOR_PENDING_CASES',
    'MORE_DETAILS_NEEDED_FROM_THE_MERCHANT',
  ],
  UAT_CRED_GENERATION: [
    'UAT_CREDS_SHARED_WITH_MERCHANT',
    'UAT_CREDS_INVALID',
    'ESCALATED_TO_BA_FOR_PENDING_CASES_TO_GET_UAT_CREDS',
  ],
  UAT_CRED_CONFIGURATION: [
    'UAT_CREDS_CONFIG_DONE_ON_CF_PORTAL',
    'ESCALATED_TO_SALES_FOR_PENDING_CASES_TO_GET_UAT_CREDS',
    'MERCHANT_TO_SHARE_UAT_CREDS_TO_CF_PRODUCT',
  ],
  PROD_CRED_GENERATION: [
    'PROD_CREDS_SHARED_WITH_MERCHANT',
    'PROD_CREDS_INVALID',
    'ESCALATED_TO_BA_FOR_PENDING_CASES_TO_GET_PROD_CREDS',
  ],
  PROD_CRED_CONFIGURATION: [
    'PROD_CREDS_CONFIG_DONE_ON_CF_PORTAL',
    'ESCALATED_TO_SALES_FOR_PENDING_CASES_TO_GET_PROD_CREDS',
    'MERCHANT_TO_SHARE_PROD_CREDS_TO_CF_PRODUCT',
  ],
  LIVE: ['TEST_TRANSACTION_COMPLETED_ON_PROD_BY_MERCHANT'],
  CLOSED: [
    'MERCHANT_DROPPED_BY_SALES',
    'MERCHANT_REJECTED_BY_THE_BANK',
    'MERCHANT_REJECTED_BY_CASHFREE',
  ],
};

const STATUSES = Object.keys(SUB_STAGES_BY_STAGE);

export const labelByStatus = _pick(LABEL_BY_STATUS, STATUSES);

export const filtersConfig = {
  'Status Filter': {
    columns: 2,
    items: Object.keys(labelByStatus),
  },
};

export enum MODAL_TYPE {
  ADD = 'ADD',
  EMPTY = '',
}

export const ADD_LEAD_FORM = `https://docs.google.com/forms/d/1WZFsFUShnzRUFzySvq4PR2lvYaTCVjn0pxFO97KoPbA/edit?entry.44948915=${localStorage.getItem(
  'merchantId',
)}`;
