import React from 'react';
import moment from 'moment';

// Styled
import { HoverCopy } from 'styled/common';

// Components
import Copy from 'components/Copy';

// Constants
import { FORMATS } from 'constants/date';

export const MODAL_TYPES = {
  ADD: 'ADD',
  DELETE: 'DELETE',
};

export const API_KEYS_COLUMN_ID = [
  {
    accessorKey: 'addedOn',
    header: 'Generated At',
    ellipsis: true,
    width: 80,
    cell: ({ addedOn }) => moment(addedOn).format(FORMATS.TIMESTAMP),
  },
  {
    accessorKey: 'generatedBy',
    header: 'Generated By',
    ellipsis: true,
    width: 80,
    cell: ({ generatedBy }) => generatedBy || '-',
  },
  {
    accessorKey: 'clientId',
    header: 'Client ID',
    ellipsis: true,
    width: 140,
    cell: ({ clientId }) => (
      <HoverCopy>
        <span>{clientId}</span>
        <Copy value={clientId} />
      </HoverCopy>
    ),
  },
  {
    accessorKey: 'clientSecret',
    header: 'Client Secret',
    width: 180,
    ellipsis: true,
  },
];
